import { Plugin } from "../types.ts";
import { colors } from "../deps.ts";
import { resolvePath } from "../util/mod.ts"
import { ensureFileSync } from "https://deno.land/std@0.151.0/fs/mod.ts";
const { green, red, bold } = colors;

// コマンドの存在を command -v を用いてチェックします
export default class Shell implements Plugin {
  private env_path: string | undefined;

  private cmds: string[] = [];
  private path: string[] = [];

  name = "shell";

  constructor(opts: {
    env_path?: string;
    cmds?: string[];
    path?: string[];
  }) {
    if (opts.env_path != undefined)
      this.env_path = resolvePath(opts.env_path)
    opts.cmds?.forEach((cmd) => {
      this.cmds.push(cmd);
    });
    opts.path?.forEach((path) => {
      this.path.push(resolvePath(path));
    });
  }

  async stat() {
    console.log(bold('env_path'))
    console.log(`・ ${this.env_path}`)

    console.log()
    console.log(bold("COMMAND"))
    const p: { cmd: string; promise: Promise<Deno.ProcessStatus> }[] = [];
    this.cmds.forEach((cmd) => {
      p.push({
        cmd: cmd,
        promise: Deno.run({
          cmd: ["sh", "-c", `command -v '${cmd}'`],
          stdin: "null",
          stdout: "null",
          stderr: "null",
        }).status(),
      });
    });

    const succe: string[] = [];
    const fails: string[] = [];

    for (const i of p) {
      if ((await i.promise).success) {
        succe.push(i.cmd);
      } else {
        fails.push(i.cmd);
      }
    }

    if (succe.length !== 0) {
      console.log(`${green("✔︎ ")} ${succe}`);
    }
    if (fails.length !== 0) {
      console.log(`${red("✘ ")} ${fails}`);
    }

    if (fails.length === 0) {
      return true;
    } else {
      return false;
    }
  }

  sync() {
    if (this.env_path === undefined) {
      if (this.path.length > 0) {
        console.error(`PATH was passed, but env_path wasn't setted`);
        return false
      } else {
        return true;
      }
    }

    const buffer: string[] = []
    buffer.push(`# ${this.env_path}: Generated by dfm Shell plugin}`)
    buffer.push(`# on ${Date()}`)

    this.path.forEach((path) => {
      // add path
      // TODO: sanitize PATH
      buffer.push(
        `export PATH='${path.replace(/\\/, "\\\\").replace(/'/, `\\\'`)}':$PATH`
      )
    })

    ensureFileSync(this.env_path);
    Deno.writeTextFileSync(this.env_path, buffer.join("\n"));
    console.log("OK")

    return true;
  }

  list() {
    console.log(bold("COMMANDS"));
    console.log(`・ ${this.cmds}`);
    console.log();

    console.log(bold("PATH"));
    this.path.forEach((path) => {
      console.log(`・ ${path}`);
    });
    return true;
  }
}
